// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"ops-dump/internal/dao/internal"
)

// jobRunsDao is the data access object for the table od_job_runs.
// You can define custom methods on it to extend its functionality as needed.
type jobRunsDao struct {
	*internal.JobRunsDao
}

var (
	// JobRuns is a globally accessible object for table od_job_runs operations.
	JobRuns = jobRunsDao{internal.NewJobRunsDao()}
)

// Add your custom methods and functionality below.
