// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"ops-dump/internal/dao/internal"
)

// jobsDao is the data access object for the table od_jobs.
// You can define custom methods on it to extend its functionality as needed.
type jobsDao struct {
	*internal.JobsDao
}

var (
	// Jobs is a globally accessible object for table od_jobs operations.
	Jobs = jobsDao{internal.NewJobsDao()}
)

// Add your custom methods and functionality below.
