// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"ops-dump/internal/dao/internal"
)

// notifyConfigDao is the data access object for the table od_notify_config.
// You can define custom methods on it to extend its functionality as needed.
type notifyConfigDao struct {
	*internal.NotifyConfigDao
}

var (
	// NotifyConfig is a globally accessible object for table od_notify_config operations.
	NotifyConfig = notifyConfigDao{internal.NewNotifyConfigDao()}
)

// Add your custom methods and functionality below.
